"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const graphql_1 = require("graphql");
const core_1 = require("@envelop/core");
const testing_1 = require("@envelop/testing");
const common_js_1 = require("../../../core/test/common.js");
const index_js_1 = require("../src/index.js");
describe('useImmediateIntrospection', () => {
    it('skips context building for introspection only operation', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('EHHH')),
        ], common_js_1.schema);
        await testInstance.execute(/* GraphQL */ `
      query {
        __typename
      }
    `);
    });
    it('skips context building for introspection only operation (alias)', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('EHHH')),
        ], common_js_1.schema);
        await testInstance.execute(/* GraphQL */ `
      query {
        some: __typename
      }
    `);
    });
    it('runs context building for operation containing non introspection fields', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('This should reject')),
        ], common_js_1.schema);
        try {
            await testInstance.execute(/* GraphQL */ `
        query {
          __schema {
            aaa: __typename
          }
          me {
            id
          }
        }
      `);
            throw new Error('Should throw.');
        }
        catch (err) {
            if (err === 'This should reject') {
                return;
            }
            throw err;
        }
    });
    it('runs context building for operation containing mutation', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('This should reject')),
        ], common_js_1.schema);
        try {
            await testInstance.execute(/* GraphQL */ `
        mutation {
          createUser {
            id
          }
        }
      `);
            throw new Error('Should throw.');
        }
        catch (err) {
            if (err === 'This should reject') {
                return;
            }
            throw err;
        }
    });
    it('runs context building for operation containing subscription', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('This should reject')),
        ], common_js_1.schema);
        try {
            await testInstance.execute(/* GraphQL */ `
        subscription {
          message
        }
      `);
            throw new Error('Should throw.');
        }
        catch (err) {
            if (err === 'This should reject') {
                return;
            }
            throw err;
        }
    });
    it('runs context building for operation containing non introspection fields', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('This should reject')),
        ], common_js_1.schema);
        try {
            await testInstance.execute(/* GraphQL */ `
        query {
          __schema {
            aaa: __typename
          }
          me {
            id
          }
        }
      `);
            throw new Error('Should throw.');
        }
        catch (err) {
            if (err === 'This should reject') {
                return;
            }
            throw err;
        }
    });
    it('skips context building for introspection operation generated by getIntrospectionQuery', async () => {
        const testInstance = (0, testing_1.createTestkit)([
            (0, index_js_1.useImmediateIntrospection)(),
            (0, core_1.useExtendContext)(() => Promise.reject('This should not reject')),
        ], common_js_1.schema);
        await testInstance.execute((0, graphql_1.getIntrospectionQuery)());
    });
});
