name: pr
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    if:
      github.event_name == 'pull_request' && github.event.pull_request.title != 'Upcoming Release
      Changes'
    name: Dependencies
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-dependencies
      cancel-in-progress: true
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yml@v1
    with:
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.BOT_GITHUB_TOKEN }}

  alpha:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@v1
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    with:
      npmTag: alpha
      buildScript: build
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  release-candidate:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@v1
    if: ${{ github.event.pull_request.title == 'Upcoming Release Changes' }}
    with:
      npmTag: rc
      restoreDeletedChangesets: true
      buildScript: build
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
