name: website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    if:
      github.event.pull_request.head.repo.full_name == github.repository || github.event_name ==
      'push'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@v1
        name: setup env
        with:
          node-version-file: '.node-version'
      - uses: the-guild-org/shared-config/website-cf@v1
        name: build and deploy website
        env:
          NEXT_BASE_PATH: ${{ github.ref == 'refs/heads/main' && '/graphql/envelop' || '' }}
          SITE_URL:
            ${{ github.ref == 'refs/heads/main' && 'https://the-guild.dev/graphql/envelop' || '' }}
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: envelop
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: ./
          buildScript: cd website && pnpm run build
          artifactDir: website/out
